# 데이터 불러오기

In [1]:
from matplotlib import rc
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import os
import pickle

import warnings
warnings.filterwarnings('ignore')


rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

# 경쟁사이용
competitor = pd.read_csv('../../data/경쟁사이용.txt', encoding='cp949')
display(competitor)
# 고객DEMO
pp_demo = pd.read_pickle("../../DATA_preprocessed/pp_demo.pickle")
display(pp_demo)
# 멤버심 여부
member = pd.read_csv('../../data/멤버십여부.txt', encoding='cp949')
display(member)
# 채널이용
channel = pd.read_csv('../../data/채널이용.txt', encoding='cp949')
display(channel)

# 상금 거래 관련
pp_purprd_prodcl = pd.read_pickle('../../DATA_preprocessed/pp_purprd_prodcl.pickle')
pp_purprd_prodcl

고객번호 제휴사  경쟁사    이용년월
0          2   D  D02  201507
1         51   D  D01  201504
2         77   D  D02  201503
3         77   D  D02  201506
4         77   D  D02  201507
...      ...  ..  ...     ...
28154  19375   B  B01  201501
28155  19375   B  B01  201507
28156  19375   C  C03  201511
28157  19376   B  B01  201506
28158  19377   B  B01  201504

[28159 rows x 4 columns]

고객번호 성별      연령대       거주지역
0          1  M    60세이상  서울특별시 강남구
1          2  M    60세이상        경기도
2          3  M    60세이상  서울특별시 은평구
3          4  F    60세이상  서울특별시 노원구
4          5  M    60세이상        경기도
...      ... ..      ...        ...
19378  19379  F  20세~24세  서울특별시 동작구
19379  19380  F  20세~24세  서울특별시 마포구
19380  19381  F  40세~44세      부산광역시
19381  19382  F  45세~49세      부산광역시
19382  19383  F  25세~29세       경상남도

[19383 rows x 4 columns]

고객번호  멤버십명    가입년월
0        11  하이마트  201512
1        21  하이마트  201506
2        37  하이마트  201306
3        43  하이마트  201403
4        44  하이마트  201411
...     ...   ...     ...
7451  19377    롭스  201411
7452  19379    롭스  201412
7453  19380    롭스  201412
7454  19381   다둥이  201506
7455  19383    롭스  201507

[7456 rows x 3 columns]

고객번호           제휴사  이용횟수
0         7  A_MOBILE/APP     4
1        14  A_MOBILE/APP     1
2        42  B_MOBILE/APP    23
3        74  A_MOBILE/APP     1
4        74  B_MOBILE/APP    30
...     ...           ...   ...
8819  19168  C_ONLINEMALL    18
8820  19291  C_ONLINEMALL     1
8821  19312  B_ONLINEMALL   137
8822  19351  C_ONLINEMALL    19
8823  19356  C_ONLINEMALL    16

[8824 rows x 3 columns]

고객번호 제휴사    영수증번호  점포코드  구매_연  구매_월  구매_일  구매시간    소분류코드   구매금액  \
0             1   A  1182697    12  2014     1     8    14  A010302   4800   
1             1   A  1239229    12  2014     1    18    15  A010302   3500   
2             1   A  1307657    12  2014     1    30    11  A010302   3900   
3             1   A  1402358    12  2014     2    18    16  A010302   3500   
4             1   A  1456379    12  2014     2    28    15  A010302   3500   
...         ...  ..      ...   ...   ...   ...   ...   ...      ...    ...   
28437049  18697   C   631324    29  2014     5    30    21  C060405   2300   
28437050  18697   C   631629    29  2014     7    20    15  C060405   2300   
28437051  18710   C  1073027    75  2015     1    22    12  C030312   7990   
28437052  18710   C  1073138    75  2015     1    29    21  C030312   7990   
28437053  19364   D   209812    13  2015     7    11    21  D040112  10500   

         대분류명 대중분류명  중분류명 제휴사_중분류명    소분류명 TYPE lev  
0          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  
1          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  
2          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  
3          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  
4          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  
...       ...   ...   ...      ...     ...  ...  ..  
28437049   식품  즉석식품  베이커리    C베이커리   페스츄리류  편의품  중가  
28437050   식품  즉석식품  베이커리    C베이커리   페스츄리류  편의품  중가  
28437051   식품   채소류   근채류     C근채류  기타한방약재  편의품  고가  
28437052   식품   채소류   근채류     C근채류  기타한방약재  편의품  고가  
28437053   식품  공산식품    과자      D과자  컵아이스크림  편의품  중가  

[28437054 rows x 17 columns]

# EDA

### pp_purprd_prodcl : 분기 Feature 만들기

In [2]:

cond_2014_1 =(pp_purprd_prodcl['구매_연']==2014)&(pp_purprd_prodcl['구매_월']<=3)
cond_2014_2 =(pp_purprd_prodcl['구매_연']==2014)&((pp_purprd_prodcl['구매_월']>3)&(pp_purprd_prodcl['구매_월']<=6))
cond_2014_3 =(pp_purprd_prodcl['구매_연']==2014)&((pp_purprd_prodcl['구매_월']>6)&(pp_purprd_prodcl['구매_월']<=9))
cond_2014_4 =(pp_purprd_prodcl['구매_연']==2014)&((pp_purprd_prodcl['구매_월']>9)&(pp_purprd_prodcl['구매_월']<=12))
cond_2015_1 =(pp_purprd_prodcl['구매_연']==2015)&(pp_purprd_prodcl['구매_월']<=3)
cond_2015_2 =(pp_purprd_prodcl['구매_연']==2015)&((pp_purprd_prodcl['구매_월']>3)&(pp_purprd_prodcl['구매_월']<=6))
cond_2015_3 =(pp_purprd_prodcl['구매_연']==2015)&((pp_purprd_prodcl['구매_월']>6)&(pp_purprd_prodcl['구매_월']<=9))
cond_2015_4 =(pp_purprd_prodcl['구매_연']==2015)&((pp_purprd_prodcl['구매_월']>9)&(pp_purprd_prodcl['구매_월']<=12))

pp_purprd_prodcl['분기']=0

pp_purprd_prodcl.loc[cond_2014_1,'분기']='14_1'
pp_purprd_prodcl.loc[cond_2014_2,'분기']='14_2'
pp_purprd_prodcl.loc[cond_2014_3,'분기']='14_3'
pp_purprd_prodcl.loc[cond_2014_4,'분기']='14_4'
pp_purprd_prodcl.loc[cond_2015_1,'분기']='15_1'
pp_purprd_prodcl.loc[cond_2015_2,'분기']='15_2'
pp_purprd_prodcl.loc[cond_2015_3,'분기']='15_3'
pp_purprd_prodcl.loc[cond_2015_4,'분기']='15_4'

pp_purprd_prodcl

고객번호 제휴사    영수증번호  점포코드  구매_연  구매_월  구매_일  구매시간    소분류코드   구매금액  \
0             1   A  1182697    12  2014     1     8    14  A010302   4800   
1             1   A  1239229    12  2014     1    18    15  A010302   3500   
2             1   A  1307657    12  2014     1    30    11  A010302   3900   
3             1   A  1402358    12  2014     2    18    16  A010302   3500   
4             1   A  1456379    12  2014     2    28    15  A010302   3500   
...         ...  ..      ...   ...   ...   ...   ...   ...      ...    ...   
28437049  18697   C   631324    29  2014     5    30    21  C060405   2300   
28437050  18697   C   631629    29  2014     7    20    15  C060405   2300   
28437051  18710   C  1073027    75  2015     1    22    12  C030312   7990   
28437052  18710   C  1073138    75  2015     1    29    21  C030312   7990   
28437053  19364   D   209812    13  2015     7    11    21  D040112  10500   

         대분류명 대중분류명  중분류명 제휴사_중분류명    소분류명 TYPE lev    분기  
0          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
1          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
2          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
3          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
4          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
...       ...   ...   ...      ...     ...  ...  ..   ...  
28437049   식품  즉석식품  베이커리    C베이커리   페스츄리류  편의품  중가  14_2  
28437050   식품  즉석식품  베이커리    C베이커리   페스츄리류  편의품  중가  14_3  
28437051   식품   채소류   근채류     C근채류  기타한방약재  편의품  고가  15_1  
28437052   식품   채소류   근채류     C근채류  기타한방약재  편의품  고가  15_1  
28437053   식품  공산식품    과자      D과자  컵아이스크림  편의품  중가  15_3  

[28437054 rows x 18 columns]

### 분석할 Feature Set

In [3]:
feature_set = {
    '대분류명' : ['패션잡화','식품','일상용품'],
    'TYPE' : ['편의품','선매품'],
    'lev' : ['중가','고가'],
    '구매금액' : ['구매금액']
}

### 구매 금액 등급화 및 변동지수(target data)생성

In [8]:
# 등급 부여 사용자 정의 함수
def make_cust_sale_grade(x, y):
    if x > fractile_list[y][7]:
        return 9
    elif x > fractile_list[y][6]:
        return 8
    elif x > fractile_list[y][5]:
        return 7
    elif x > fractile_list[y][4]:
        return 6
    elif x > fractile_list[y][3]:
        return 5
    elif x > fractile_list[y][2]:
        return 4
    elif x > fractile_list[y][1]:
        return 3
    elif x > fractile_list[y][0]:
        return 2
    else:
        return 1 
    

pp_datasets = pp_demo['고객번호']
for i in feature_set.keys():
    for j in range(len(feature_set[i])):
        option = 'sum'
        if feature_set[i][j] == '구매금액':
            pp_pivot = pp_purprd_prodcl.pivot_table(index=['고객번호'], columns=['분기'], values='구매금액', aggfunc=(f'{option}'), fill_value=0)
        else:
            pp_pivot = pp_purprd_prodcl[pp_purprd_prodcl[i]==feature_set[i][j]].pivot_table(index=['고객번호'], columns=['분기'], values='구매금액', aggfunc=(f'{option}'), fill_value=0)
        
        # 등급 분위수 딕셔너리 생성
        Q_list = ['14_1', '14_2', '14_3', '14_4', '15_1', '15_2', '15_3', '15_4']
        fractile_list = {}
        for Q in Q_list:
            fractiles = []
            for percentile in [4, 11, 23, 40, 60, 77, 89, 96]:
                fractiles.append(np.percentile(pp_pivot[Q], percentile))
                fractile_list[Q] = fractiles
        # 고개별 분기별 feature 별 매출 등급 생성        
        for Q in Q_list:
            pp_pivot[str(Q)] = pp_pivot.apply(lambda row: make_cust_sale_grade(row[Q], Q), axis=1)
            
        # 분기별 매출 변화량 feature 생성 
        pp_pivot[str(feature_set[i][j])+'_14_2-14_1'] = (pp_pivot['14_2']-pp_pivot['14_1'])*1
        pp_pivot[str(feature_set[i][j])+'_14_3-14_2'] = (pp_pivot['14_3']-pp_pivot['14_2'])*1.1
        pp_pivot[str(feature_set[i][j])+'_14_4-14_3'] = (pp_pivot['14_4']-pp_pivot['14_3'])*1.2
        pp_pivot[str(feature_set[i][j])+'_15_1-14_4'] = (pp_pivot['15_1']-pp_pivot['14_4'])*1.3
        pp_pivot[str(feature_set[i][j])+'_15_2-15_1'] = (pp_pivot['15_2']-pp_pivot['15_1'])*1.4
        pp_pivot[str(feature_set[i][j])+'_15_3-15_2'] = (pp_pivot['15_3']-pp_pivot['15_2'])*1.5
        pp_pivot[str(feature_set[i][j])+'_15_4-15_3'] = (pp_pivot['15_4']-pp_pivot['14_3'])*1.6

        pp_pivot = pp_pivot.drop(columns=Q_list).reset_index()

        # 고객별 분기별 총매출 변동지수(target data) 생성
        if feature_set[i][j] == '구매금액':
            # 변동지수(변화량)에 가중치 부여 (가중치 최근 분기 일수록 옾은 가중치 부여)
            # coeff_var = np.linspace(1,1.5,num=6) # 1부터 0.1씩 증가
            coeff_var=[1, 1, 1, 1, 1, 1]
            pp_pivot[str(feature_set[i][j])+'_15_3분기_변동지수'] = (pp_pivot[str(feature_set[i][j])+'_14_2-14_1'])*coeff_var[0] +\
                                    (pp_pivot[str(feature_set[i][j])+'_14_3-14_2'])*coeff_var[1] +\
                                    (pp_pivot[str(feature_set[i][j])+'_14_4-14_3'])*coeff_var[2] +\
                                    (pp_pivot[str(feature_set[i][j])+'_15_1-14_4'])*coeff_var[3] +\
                                    (pp_pivot[str(feature_set[i][j])+'_15_2-15_1'])*coeff_var[4] +\
                                    (pp_pivot[str(feature_set[i][j])+'_15_3-15_2'])*coeff_var[5]

            pp_pivot[str(feature_set[i][j])+'_15_4분기_변동지수'] = (pp_pivot[str(feature_set[i][j])+'_14_3-14_2'])*coeff_var[0] +\
                                    (pp_pivot[str(feature_set[i][j])+'_14_4-14_3'])*coeff_var[1] +\
                                    (pp_pivot[str(feature_set[i][j])+'_15_1-14_4'])*coeff_var[2] +\
                                    (pp_pivot[str(feature_set[i][j])+'_15_2-15_1'])*coeff_var[3] +\
                                    (pp_pivot[str(feature_set[i][j])+'_15_3-15_2'])*coeff_var[4] +\
                                    (pp_pivot[str(feature_set[i][j])+'_15_4-15_3'])*coeff_var[5]
        else:
            pass
        
        pp_datasets = pd.merge(pp_datasets, pp_pivot, on='고객번호', how='left')
        
# 변동지수 생성 사용자 함수 : 고객별 분기 매출 등급 변화량 지수화 
def find_RP_by_cus(x):
    if x < 0:
        return 1 # 감소
    else:
        return 0 # 증가
pp_datasets['구매금액_15_3분기_변동지수'] = pp_datasets['구매금액_15_3분기_변동지수'].apply(find_RP_by_cus)
pp_datasets['구매금액_15_4분기_변동지수'] = pp_datasets['구매금액_15_4분기_변동지수'].apply(find_RP_by_cus)
pp_datasets.fillna(0)
pp_datasets.rename(index={'분기':'index'})
pp_datasets

고객번호  패션잡화_14_2-14_1  패션잡화_14_3-14_2  패션잡화_14_4-14_3  패션잡화_15_1-14_4  \
0          1             1.0             0.0             0.0             0.0   
1          2             0.0             1.1            -1.2             1.3   
2          3             0.0             0.0             0.0             0.0   
3          4             1.0            -1.1            -2.4             1.3   
4          5             0.0             0.0            -4.8             0.0   
...      ...             ...             ...             ...             ...   
19378  19379             0.0             3.3             1.2             0.0   
19379  19380             0.0             0.0             0.0             0.0   
19380  19381             0.0             0.0             0.0             5.2   
19381  19382             0.0             0.0             0.0             3.9   
19382  19383             0.0             0.0             0.0             0.0   

       패션잡화_15_2-15_1  패션잡화_15_3-15_2  패션잡화_15_4-15_3  식품_14_2-14_1  \
0                 0.0             0.0            -1.6           1.0   
1                -1.4             1.5            -1.6           0.0   
2                 0.0             0.0             3.2           0.0   
3                 0.0             1.5            -1.6           2.0   
4                 0.0             0.0             0.0          -1.0   
...               ...             ...             ...           ...   
19378            -1.4             1.5             3.2           0.0   
19379             4.2            -4.5             6.4           0.0   
19380            -5.6             4.5             3.2           0.0   
19381            -4.2             0.0             0.0           0.0   
19382             0.0             7.5             6.4           0.0   

       식품_14_3-14_2  ...  고가_15_4-15_3  구매금액_14_2-14_1  구매금액_14_3-14_2  \
0              -3.3  ...          -3.2               0             0.0   
1              -1.1  ...          -1.6              -1             1.1   
2               1.1  ...          -1.6               0             0.0   
3              -3.3  ...           0.0               2             0.0   
4              -1.1  ...           3.2              -1             0.0   
...             ...  ...           ...             ...             ...   
19378           0.0  ...           6.4               0             0.0   
19379           0.0  ...           6.4               0             0.0   
19380           0.0  ...           6.4               0             0.0   
19381           0.0  ...           4.8               0             0.0   
19382           0.0  ...           6.4               0             0.0   

       구매금액_14_4-14_3  구매금액_15_1-14_4  구매금액_15_2-15_1  구매금액_15_3-15_2  \
0                 1.2            -1.3             0.0             0.0   
1                -2.4             2.6            -1.4             1.5   
2                -1.2             0.0             0.0             0.0   
3                -1.2             0.0             0.0             0.0   
4                -4.8             5.2            -4.2            -1.5   
...               ...             ...             ...             ...   
19378             2.4             0.0             1.4            -3.0   
19379             0.0             0.0             0.0             0.0   
19380             0.0             2.6             1.4             1.5   
19381             0.0             1.3             1.4             1.5   
19382             0.0             0.0             0.0             3.0   

       구매금액_15_4-15_3  구매금액_15_3분기_변동지수  구매금액_15_4분기_변동지수  
0                -1.6                 1                 1  
1                -1.6                 0                 1  
2                -1.6                 1                 1  
3                -3.2                 0                 1  
4                 1.6                 1                 1  
...               ...               ...               ...  
19378   

# 머신러닝

## 라이브러리 import

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier


## 머신러닝 평가 지표 출력 사용자 함수 생성

In [10]:
def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
          F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

## 머신러닝 사용자 함수

In [13]:
def ml(df_final,pp_demo):
    # 고객 Demo Data -> One-Hot 인코딩
    pp_demo = pd.get_dummies(pp_demo)
    # Merge
    final_df = pd.merge(pp_demo, df_final, on='고객번호').fillna(0)
    display(final_df)

    a = pd.Series(final_df.columns, name='컬럼')[pd.Series(final_df.columns, name='컬럼').str.contains('15_3-15_2')].values.tolist()
    b = pd.Series(final_df.columns, name='컬럼')[pd.Series(final_df.columns, name='컬럼').str.contains('15_4-15_3')].values.tolist()
    li = ['구매금액_15_3분기_변동지수','구매금액_15_4분기_변동지수']
    li = li + a + b
    X_train = final_df.drop(columns=li)
    for i in X_train.columns:
        X_train[i]
    y_train = final_df['구매금액_15_3분기_변동지수']
    
    a = pd.Series(final_df.columns, name='컬럼')[pd.Series(final_df.columns, name='컬럼').str.contains('14_2-14_1')].values.tolist()
    b = pd.Series(final_df.columns, name='컬럼')[pd.Series(final_df.columns, name='컬럼').str.contains('15_4-15_3')].values.tolist()
    li = ['구매금액_15_3분기_변동지수','구매금액_15_4분기_변동지수']
    li = li + a + b
    X_test = final_df.drop(columns=li)
    y_test = final_df['구매금액_15_4분기_변동지수']


    # 로지스틱 회귀로 학습,예측 및 평가 수행. 
    lr_clf = LogisticRegression(solver='liblinear')
    dt_clf = DecisionTreeClassifier()
    rf_clf = RandomForestClassifier()
    lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=50, n_jobs=-1, boost_from_average=False)
    xgb_clf = XGBClassifier(n_estimators=1000, n_jobs=-1 )
    
    lr_clf.fit(X_train , y_train)
    dt_clf.fit(X_train , y_train)
    rf_clf.fit(X_train , y_train)
    lgbm_clf.fit(X_train, y_train)
    xgb_clf.fit(X_train, y_train)
    
    pred_lr = lr_clf.predict(X_test)
    pred_dt = dt_clf.predict(X_test)
    pred_rf = rf_clf.predict(X_test)
    pred_lgbm = lgbm_clf.predict(X_test)
    pred_xgb = xgb_clf.predict(X_test)
    
    pred_proba_lr = lr_clf.predict_proba(X_test)[:, 1]
    pred_proba_dt = dt_clf.predict_proba(X_test)[:, 1]
    pred_proba_rf = rf_clf.predict_proba(X_test)[:, 1]
    pred_proba_lgbm = lgbm_clf.predict_proba(X_test)[:, 1]
    pred_proba_xgb = xgb_clf.predict_proba(X_test)[:, 1]
    
    get_clf_eval(y_test, pred_lr, pred_proba_lr)
    get_clf_eval(y_test, pred_dt, pred_proba_dt)
    get_clf_eval(y_test, pred_rf, pred_proba_rf)
    get_clf_eval(y_test, pred_lgbm, pred_proba_lgbm)
    get_clf_eval(y_test, pred_xgb, pred_proba_xgb)
    
    return pred_lr
pred_lr = ml(pp_datasets,pp_demo)
pred_lr

고객번호  성별_F  성별_M  연령대_19세이하  연령대_20세~24세  연령대_25세~29세  연령대_30세~34세  \
0          1     0     1          0            0            0            0   
1          2     0     1          0            0            0            0   
2          3     0     1          0            0            0            0   
3          4     1     0          0            0            0            0   
4          5     0     1          0            0            0            0   
...      ...   ...   ...        ...          ...          ...          ...   
19378  19379     1     0          0            1            0            0   
19379  19380     1     0          0            1            0            0   
19380  19381     1     0          0            0            0            0   
19381  19382     1     0          0            0            0            0   
19382  19383     1     0          0            0            1            0   

       연령대_35세~39세  연령대_40세~44세  연령대_45세~49세  ...  고가_15_4-15_3  \
0                0            0            0  ...          -3.2   
1                0            0            0  ...          -1.6   
2                0            0            0  ...          -1.6   
3                0            0            0  ...           0.0   
4                0            0            0  ...           3.2   
...            ...          ...          ...  ...           ...   
19378            0            0            0  ...           6.4   
19379            0            0            0  ...           6.4   
19380            0            1            0  ...           6.4   
19381            0            0            1  ...           4.8   
19382            0            0            0  ...           6.4   

       구매금액_14_2-14_1  구매금액_14_3-14_2  구매금액_14_4-14_3  구매금액_15_1-14_4  \
0                   0             0.0             1.2            -1.3   
1                  -1             1.1            -2.4             2.6   
2                   0             0.0            -1.2             0.0   
3                   2             0.0            -1.2             0.0   
4                  -1             0.0            -4.8             5.2   
...               ...             ...             ...             ...   
19378               0             0.0             2.4             0.0   
19379               0             0.0             0.0             0.0   
19380               0             0.0             0.0             2.6   
19381               0             0.0             0.0             1.3   
19382               0             0.0             0.0             0.0   

       구매금액_15_2-15_1  구매금액_15_3-15_2  구매금액_15_4-15_3  구매금액_15_3분기_변동지수  \
0                 0.0             0.0            -1.6                 1   
1                -1.4             1.5            -1.6                 0   
2                 0.0             0.0            -1.6                 1   
3                 0.0             0.0            -3.2                 0   
4                -4.2            -1.5             1.6                 1   
...               ...             ...             ...               ...   
19378             1.4            -3.0             4.8                 0   
19379             0.0             0.0             6.4                 0   
19380             1.4             1.5             4.8                 0   
19381             1.4             1.5             4.8                 0   
19382             0.0             3.0             4.8                 0   

       구매금액_15_4분기_변동지수  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  
...                 ...  
19378                 0  
19379                 0  
19380                 0  
19381                 0  
19382                 0  

[19383 rows x 112 columns]

오차 행렬
[[7900 2202]
 [2972 6309]]
정확도: 0.7331, 정밀도: 0.7413, 재현율: 0.6798,          F1: 0.7092, AUC:0.8169
오차 행렬
[[6169 3933]
 [4005 5276]]
정확도: 0.5905, 정밀도: 0.5729, 재현율: 0.5685,          F1: 0.5707, AUC:0.5896
오차 행렬
[[7555 2547]
 [3864 5417]]
정확도: 0.6692, 정밀도: 0.6802, 재현율: 0.5837,          F1: 0.6282, AUC:0.7382
오차 행렬
[[7498 2604]
 [3187 6094]]
정확도: 0.7012, 정밀도: 0.7006, 재현율: 0.6566,          F1: 0.6779, AUC:0.7660
오차 행렬
[[7292 2810]
 [3300 5981]]
정확도: 0.6848, 정밀도: 0.6804, 재현율: 0.6444,          F1: 0.6619, AUC:0.7515


array([1, 1, 1, ..., 0, 0, 0])

In [215]:
pp_datasets

고객번호  패션잡화_14_2-14_1  패션잡화_14_3-14_2  패션잡화_14_4-14_3  패션잡화_15_1-14_4  \
0          1             1.0             0.0             0.0             0.0   
1          2             0.0             1.1            -1.2             1.3   
2          3             0.0             0.0             0.0             0.0   
3          4             1.0            -1.1            -2.4             1.3   
4          5             0.0             0.0            -4.8             0.0   
...      ...             ...             ...             ...             ...   
19378  19379             0.0             3.3             1.2             0.0   
19379  19380             0.0             0.0             0.0             0.0   
19380  19381             0.0             0.0             0.0             5.2   
19381  19382             0.0             0.0             0.0             3.9   
19382  19383             0.0             0.0             0.0             0.0   

       패션잡화_15_2-15_1  패션잡화_15_3-15_2  패션잡화_15_4-15_3  식품_14_2-14_1  \
0                 0.0             0.0            -1.6           1.0   
1                -1.4             1.5            -1.6           0.0   
2                 0.0             0.0             3.2           0.0   
3                 0.0             1.5            -1.6           2.0   
4                 0.0             0.0             0.0          -1.0   
...               ...             ...             ...           ...   
19378            -1.4             1.5             3.2           0.0   
19379             4.2            -4.5             6.4           0.0   
19380            -5.6             4.5             3.2           0.0   
19381            -4.2             0.0             0.0           0.0   
19382             0.0             7.5             6.4           0.0   

       식품_14_3-14_2  ...  고가_15_4-15_3  구매금액_14_2-14_1  구매금액_14_3-14_2  \
0              -3.3  ...          -3.2               0             0.0   
1              -1.1  ...          -1.6              -1             1.1   
2               1.1  ...          -1.6               0             0.0   
3              -3.3  ...           0.0               2             0.0   
4              -1.1  ...           3.2              -1             0.0   
...             ...  ...           ...             ...             ...   
19378           0.0  ...           6.4               0             0.0   
19379           0.0  ...           6.4               0             0.0   
19380           0.0  ...           6.4               0             0.0   
19381           0.0  ...           4.8               0             0.0   
19382           0.0  ...           6.4               0             0.0   

       구매금액_14_4-14_3  구매금액_15_1-14_4  구매금액_15_2-15_1  구매금액_15_3-15_2  \
0                 1.2            -1.3             0.0             0.0   
1                -2.4             2.6            -1.4             1.5   
2                -1.2             0.0             0.0             0.0   
3                -1.2             0.0             0.0             0.0   
4                -4.8             5.2            -4.2            -1.5   
...               ...             ...             ...             ...   
19378             2.4             0.0             1.4            -3.0   
19379             0.0             0.0             0.0             0.0   
19380             0.0             2.6             1.4             1.5   
19381             0.0             1.3             1.4             1.5   
19382             0.0             0.0             0.0             3.0   

       구매금액_15_4-15_3  구매금액_15_3분기_변동지수  구매금액_15_4분기_변동지수  
0                -1.6                 1                 1  
1                -1.6                 0                 1  
2                -1.6                 1                 1  
3                -3.2                 0                 1  
4                 1.6                 1                 1  
...               ...               ...               ...  
19378   

# 추천 시스템

## 고객별 대중분류명별 분기별 총매출 sum

In [204]:
len(reco_cust_num)

8511

In [216]:
# 추천 시스템용 데이터(recommend)
reco = pd.merge(pp_demo, pp_datasets, on='고객번호', how='left')
reco_cust = reco[pred_lr==1]
reco_cust_num=reco_cust['고객번호'].values
reco_cust_num

array([    1,     2,     3, ..., 19346, 19360, 19364])

In [226]:
reco_cust_num

array([    1,     2,     3, ..., 19346, 19360, 19364])

In [229]:
reco_cust_pv = pp_purprd_prodcl.pivot_table(index=['고객번호','대중분류명'],columns='분기',values='구매금액',aggfunc='sum').reset_index()
reco_cust_pv=reco_cust_pv[reco_cust_pv['고객번호'].isin(reco_cust_num)]
reco_cust_pv=reco_cust_pv.fillna(0)
reco_cust_pv=reco_cust_pv.iloc[:,:-1]
reco_cust_pv

분기       고객번호   대중분류명      14_1       14_2       14_3       14_4      15_1  \
0           1     가공육       0.0        0.0        0.0        0.0   10000.0   
1           1     감미료       0.0        0.0        0.0    35030.0       0.0   
2           1  건강기능식품  860000.0  1911870.0   188100.0    27000.0       0.0   
3           1     건어류       0.0        0.0        0.0     3750.0       0.0   
4           1      곡류       0.0        0.0        0.0    27900.0  107000.0   
...       ...     ...       ...        ...        ...        ...       ...   
749451  19364    케어용품       0.0  1419720.0  1209300.0  1478000.0  835200.0   
749452  19364    패션잡화       0.0        0.0        0.0   600500.0       0.0   
749453  19364     편집샵       0.0        0.0   159000.0   253600.0       0.0   
749454  19364     해산물       0.0        0.0     8990.0        0.0       0.0   
749455  19364     화장품       0.0   189350.0   292600.0   485200.0  114600.0   

분기          15_2       15_3  
0            0.0        0.0  
1            0.0        0.0  
2            0.0        0.0  
3         5990.0        0.0  
4            0.0        0.0  
...          ...        ...  
749451  621890.0  1322500.0  
749452  141990.0        0.0  
749453       0.0        0.0  
749454       0.0        0.0  
749455  848600.0   847100.0  

[326720 rows x 9 columns]

 ## 이전 7분기의 고객별 대중분류별 총매출의 추세

In [230]:
grad_li = []
for i in range(len(reco_cust_pv)):
    
    z=np.polyfit(np.array([1.,2.,3.,4.,5.,6.,7.])*100,reco_cust_pv.iloc[i,2:].values.astype(float),1)[0]
    grad_li.append(z)
# len(grad_li)
reco_cust_pv['gradient'] = np.array([grad_li]).reshape(-1,1)
reco_cust_pv

분기       고객번호   대중분류명      14_1       14_2       14_3       14_4      15_1  \
0           1     가공육       0.0        0.0        0.0        0.0   10000.0   
1           1     감미료       0.0        0.0        0.0    35030.0       0.0   
2           1  건강기능식품  860000.0  1911870.0   188100.0    27000.0       0.0   
3           1     건어류       0.0        0.0        0.0     3750.0       0.0   
4           1      곡류       0.0        0.0        0.0    27900.0  107000.0   
...       ...     ...       ...        ...        ...        ...       ...   
749451  19364    케어용품       0.0  1419720.0  1209300.0  1478000.0  835200.0   
749452  19364    패션잡화       0.0        0.0        0.0   600500.0       0.0   
749453  19364     편집샵       0.0        0.0   159000.0   253600.0       0.0   
749454  19364     해산물       0.0        0.0     8990.0        0.0       0.0   
749455  19364     화장품       0.0   189350.0   292600.0   485200.0  114600.0   

분기          15_2       15_3      gradient  
0            0.0        0.0  3.571429e+00  
1            0.0        0.0 -2.142608e-15  
2            0.0        0.0 -2.354229e+03  
3         5990.0        0.0  4.278571e+00  
4            0.0        0.0  3.821429e+01  
...          ...        ...           ...  
749451  621890.0  1322500.0  7.134786e+02  
749452  141990.0        0.0  1.014214e+02  
749453       0.0        0.0 -5.678571e+01  
749454       0.0        0.0 -3.210714e+00  
749455  848600.0   847100.0  1.314929e+03  

[326720 rows x 10 columns]

In [232]:
# 고객별 추천할 대중분류를 딕셔너리에 담기 
recom_dict = {}
for i in reco_cust_num:
    reco_group=reco_cust_pv[['고객번호','대중분류명','gradient']].groupby(['고객번호'])
    recom_dict[i] = reco_group.get_group((i)).sort_values(by='gradient')['대중분류명'].iloc[0]

recom_dict

{1: '건강기능식품',
 2: '레져',
 3: '주류',
 4: '패션잡화',
 5: '유제품',
 6: '공산식품',
 9: '디자이너',
 10: '명품',
 11: '대형가구',
 14: '기타의류',
 15: '명품',
 18: '디자이너',
 20: '농산물',
 22: '명품',
 23: '레져',
 24: '레져',
 25: '건강기능식품',
 29: '명품',
 32: '해산물',
 34: '육류',
 36: '대형가구',
 39: '디자이너',
 41: '공산식품',
 46: '명품',
 47: '디자이너',
 48: '디자이너',
 50: '패션잡화',
 51: '대형가전',
 52: '기타의류',
 53: '레져',
 54: '화장품',
 56: '명품',
 57: '곡류',
 58: '기타',
 59: '패션잡화',
 61: '편집샵',
 62: '유아용품',
 64: '즉석식품',
 65: '생활가전',
 66: '편집샵',
 68: '시계',
 70: '명품',
 71: '감미료',
 73: '디자이너',
 74: '편집샵',
 75: '곡류',
 77: '패션잡화',
 84: '편집샵',
 87: '대형가전',
 88: '레져',
 89: '남성의류',
 91: '농산물',
 96: '레져',
 97: '명품',
 99: '디자이너',
 100: '화장품',
 102: '명품',
 103: '과일류',
 105: '곡류',
 109: '유아용품',
 110: '스포츠의류',
 111: '우육',
 113: '기타',
 114: '여성의류',
 115: '농산물',
 116: '화장품',
 118: '화장품',
 119: '편집샵',
 124: '디자이너',
 125: '명품',
 127: '편집샵',
 128: '조류',
 130: '편집샵',
 131: '기타',
 132: '즉석식품',
 135: '디자이너',
 136: '스포츠의류',
 138: '명품',
 139: '디자이너',
 140: '화장품',
 144: '채소류'

In [55]:
cust_no = 1

reco = pp_purprd_prodcl[pp_purprd_prodcl['분기']!='15_4']
for i in [1]:
    
    for i in range(len(Q_list[:-1]):
        reco_ = reco[reco['분기']==Q_list[i]]
        reco_gb_1 = reco_.groupby(by=['고객번호', '대중분류명'])['구매금액'].sum().reset_index()
        display(reco_gb_1)


            reco_gb[reco_gb['고객번호']==i].sort_values(by='구매금액', ascending=False)[:2]
        reco_gb[reco_gb['고객번호']==i].sort_values(by='구매금액', ascending=False)[:2]




고객번호   대중분류명    구매금액
0           1  건강기능식품  860000
1           1    공산식품  333700
2           1      기타  711900
3           1    기타의류  118840
4           1    남성의류  485640
...       ...     ...     ...
408643  19336    공산식품   62600
408644  19336   스포츠의류  387000
408645  19337    공산식품    5360
408646  19337      담배    5200
408647  19337     유제품    5960

[408648 rows x 3 columns]

고객번호   대중분류명     구매금액
0           1  건강기능식품  1911870
1           1    공산식품   228830
2           1      기타    66500
3           1    기타의류   241240
4           1    남성의류  1179710
...       ...     ...      ...
419269  19364    기타의류     3150
419270  19364   스포츠의류   336900
419271  19364    위생용품    24700
419272  19364    케어용품  1419720
419273  19364     화장품   189350

[419274 rows x 3 columns]

고객번호   대중분류명     구매금액
0           1  건강기능식품  1911870
1           1    공산식품   228830
2           1      기타    66500
3           1    기타의류   241240
4           1    남성의류  1179710
...       ...     ...      ...
419269  19364    기타의류     3150
419270  19364   스포츠의류   336900
419271  19364    위생용품    24700
419272  19364    케어용품  1419720
419273  19364     화장품   189350

[419274 rows x 3 columns]

고객번호   대중분류명     구매금액
0           1  건강기능식품   188100
1           1    공산식품   555610
2           1      기타   463400
3           1    기타의류    70000
4           1    남성의류  2361700
...       ...     ...      ...
430233  19373    케어용품     2000
430234  19379    공산식품    20000
430235  19379    케어용품    19400
430236  19379    패션잡화    78000
430237  19379     화장품    12900

[430238 rows x 3 columns]

고객번호   대중분류명     구매금액
0           1  건강기능식품   188100
1           1    공산식품   555610
2           1      기타   463400
3           1    기타의류    70000
4           1    남성의류  2361700
...       ...     ...      ...
430233  19373    케어용품     2000
430234  19379    공산식품    20000
430235  19379    케어용품    19400
430236  19379    패션잡화    78000
430237  19379     화장품    12900

[430238 rows x 3 columns]

고객번호   대중분류명    구매금액
0           1     감미료   35030
1           1  건강기능식품   27000
2           1     건어류    3750
3           1      곡류   27900
4           1    공산식품  542780
...       ...     ...     ...
450453  19380    공산식품   16800
450454  19380      기타    3000
450455  19380    생활용품    9900
450456  19380    케어용품   15000
450457  19380     화장품  478000

[450458 rows x 3 columns]

고객번호   대중분류명    구매금액
0           1     감미료   35030
1           1  건강기능식품   27000
2           1     건어류    3750
3           1      곡류   27900
4           1    공산식품  542780
...       ...     ...     ...
450453  19380    공산식품   16800
450454  19380      기타    3000
450455  19380    생활용품    9900
450456  19380    케어용품   15000
450457  19380     화장품  478000

[450458 rows x 3 columns]

고객번호 대중분류명    구매금액
0           1   가공육   10000
1           1    곡류  107000
2           1  공산식품  849780
3           1   과일류   16821
4           1    기타  133240
...       ...   ...     ...
443017  19382  케어용품   24100
443018  19382  패션잡화    5900
443019  19382   편집샵   49900
443020  19382   해산물    5180
443021  19382  헬스케어    5800

[443022 rows x 3 columns]

고객번호 대중분류명    구매금액
0           1   가공육   10000
1           1    곡류  107000
2           1  공산식품  849780
3           1   과일류   16821
4           1    기타  133240
...       ...   ...     ...
443017  19382  케어용품   24100
443018  19382  패션잡화    5900
443019  19382   편집샵   49900
443020  19382   해산물    5180
443021  19382  헬스케어    5800

[443022 rows x 3 columns]

고객번호 대중분류명     구매금액
0           1   건어류     5990
1           1  공산식품   324360
2           1   과일류    80360
3           1    기타   534240
4           1  남성의류  1879550
...       ...   ...      ...
450492  19382   해산물    11236
450493  19382   해조류     6000
450494  19382   화장품    17900
450495  19383  공산식품     4000
450496  19383  케어용품    23000

[450497 rows x 3 columns]

고객번호 대중분류명     구매금액
0           1   건어류     5990
1           1  공산식품   324360
2           1   과일류    80360
3           1    기타   534240
4           1  남성의류  1879550
...       ...   ...      ...
450492  19382   해산물    11236
450493  19382   해조류     6000
450494  19382   화장품    17900
450495  19383  공산식품     4000
450496  19383  케어용품    23000

[450497 rows x 3 columns]

고객번호 대중분류명     구매금액
0           1  공산식품   325670
1           1    기타  1000800
2           1   농산물    54000
3           1  디자이너   476900
4           1  레스토랑    44800
...       ...   ...      ...
452120  19383  즉석식품    23320
452121  19383  케어용품   275330
452122  19383  패션잡화   306200
452123  19383   편집샵   148900
452124  19383   화장품    70200

[452125 rows x 3 columns]

In [28]:
import pandas as pd

In [19]:
pp_purprd_prodcl[pp_purprd_prodcl['분기']!='15_4']

고객번호 제휴사    영수증번호  점포코드  구매_연  구매_월  구매_일  구매시간    소분류코드   구매금액  \
0             1   A  1182697    12  2014     1     8    14  A010302   4800   
1             1   A  1239229    12  2014     1    18    15  A010302   3500   
2             1   A  1307657    12  2014     1    30    11  A010302   3900   
3             1   A  1402358    12  2014     2    18    16  A010302   3500   
4             1   A  1456379    12  2014     2    28    15  A010302   3500   
...         ...  ..      ...   ...   ...   ...   ...   ...      ...    ...   
28437049  18697   C   631324    29  2014     5    30    21  C060405   2300   
28437050  18697   C   631629    29  2014     7    20    15  C060405   2300   
28437051  18710   C  1073027    75  2015     1    22    12  C030312   7990   
28437052  18710   C  1073138    75  2015     1    29    21  C030312   7990   
28437053  19364   D   209812    13  2015     7    11    21  D040112  10500   

         대분류명 대중분류명  중분류명 제휴사_중분류명    소분류명 TYPE lev    분기  
0          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
1          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
2          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
3          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
4          식품   유제품  축산가공    A축산가공     유제품  편의품  중가  14_1  
...       ...   ...   ...      ...     ...  ...  ..   ...  
28437049   식품  즉석식품  베이커리    C베이커리   페스츄리류  편의품  중가  14_2  
28437050   식품  즉석식품  베이커리    C베이커리   페스츄리류  편의품  중가  14_3  
28437051   식품   채소류   근채류     C근채류  기타한방약재  편의품  고가  15_1  
28437052   식품   채소류   근채류     C근채류  기타한방약재  편의품  고가  15_1  
28437053   식품  공산식품    과자      D과자  컵아이스크림  편의품  중가  15_3  

[25006807 rows x 18 columns]